# Generated by Django 5.1.6

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BlockingReason',
            fields=[
                ('code', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    'event_type',
                    models.CharField(
                        choices=[('PRODUCT_APPROVED', 'PRODUCT_APPROVED'), ('PRODUCT_DECLINED', 'PRODUCT_DECLINED')],
                        max_length=32,
                    ),
                ),
                ('product_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ModerationCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED')], max_length=16)),
                (
                    'queue_status',
                    models.CharField(
                        choices=[('PENDING', 'PENDING'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')],
                        db_index=True,
                        default='PENDING',
                        max_length=16,
                    ),
                ),
                ('snapshot_before', models.JSONField(blank=True, null=True)),
                ('snapshot_after', models.JSONField(default=dict)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=255, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decline_comment', models.CharField(blank=True, max_length=500)),
                ('decline_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'decline_reason',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cards',
                        to='moderation_api.blockingreason',
                    ),
                ),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='moderationcard',
            index=models.Index(fields=['queue_status', 'created_at'], name='moderation__queue_s_3dde55_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcard',
            index=models.Index(fields=['product_id', 'queue_status'], name='moderation__product__733eca_idx'),
        ),
    ]
