from django.urls import path

from .views import (
    DashboardOverviewView,
    DashboardStatsView,
    FulfillView,
    InvoiceAcceptView,
    InvoiceDetailView,
    InvoicesView,
    ModerationEventsView,
    ProductDetailView,
    ProductsView,
    PublicProductBatchView,
    PublicProductDetailView,
    PublicProductListView,
    PublicProductSimilarView,
    PublicSkuDetailView,
    ReserveView,
    SellerProfileView,
    SkuDetailView,
    SkuMutationView,
    SkuListByProductView,
    UnreserveView,
)


urlpatterns = [
    # Seller profile (canonical + legacy)
    path('sellers/me', SellerProfileView.as_view(), name='b2b-sellers-me-no-slash'),
    path('sellers/me/', SellerProfileView.as_view(), name='b2b-sellers-me'),
    path('profile', SellerProfileView.as_view(), name='b2b-profile-no-slash'),
    path('profile/', SellerProfileView.as_view(), name='b2b-profile'),
    # Dashboard (legacy extensions, not in unified OpenAPI)
    path('dashboard/overview', DashboardOverviewView.as_view(), name='b2b-dashboard-overview-no-slash'),
    path('dashboard/overview/', DashboardOverviewView.as_view(), name='b2b-dashboard-overview'),
    path('dashboard/stats', DashboardStatsView.as_view(), name='b2b-dashboard-stats-no-slash'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='b2b-dashboard-stats'),
    # Products (seller)
    path('products', ProductsView.as_view(), name='b2b-products-no-slash'),
    path('products/', ProductsView.as_view(), name='b2b-products'),
    path('products/<uuid:product_id>', ProductDetailView.as_view(), name='b2b-product-detail-no-slash'),
    path('products/<uuid:product_id>/', ProductDetailView.as_view(), name='b2b-product-detail'),
    path('products/<uuid:id>', ProductDetailView.as_view(), name='b2b-product-detail-legacy-no-slash'),
    path('products/<uuid:id>/', ProductDetailView.as_view(), name='b2b-product-detail-legacy'),
    # SKUs
    path('products/<uuid:product_id>/skus', SkuListByProductView.as_view(), name='b2b-product-skus-no-slash'),
    path('products/<uuid:product_id>/skus/', SkuListByProductView.as_view(), name='b2b-product-skus'),
    path('skus', SkuMutationView.as_view(), name='b2b-skus-no-slash'),
    path('skus/', SkuMutationView.as_view(), name='b2b-skus'),
    path('skus/<uuid:sku_id>', SkuDetailView.as_view(), name='b2b-sku-detail-no-slash'),
    path('skus/<uuid:sku_id>/', SkuDetailView.as_view(), name='b2b-sku-detail'),
    path('skus/<uuid:id>', SkuDetailView.as_view(), name='b2b-sku-detail-legacy-no-slash'),
    path('skus/<uuid:id>/', SkuDetailView.as_view(), name='b2b-sku-detail-legacy'),
    # Invoices
    path('invoices', InvoicesView.as_view(), name='b2b-invoices-no-slash'),
    path('invoices/', InvoicesView.as_view(), name='b2b-invoices'),
    path('invoices/<uuid:invoice_id>', InvoiceDetailView.as_view(), name='b2b-invoice-detail-no-slash'),
    path('invoices/<uuid:invoice_id>/', InvoiceDetailView.as_view(), name='b2b-invoice-detail'),
    path('invoices/<uuid:invoice_id>/accept', InvoiceAcceptView.as_view(), name='b2b-invoices-accept-no-slash'),
    path('invoices/<uuid:invoice_id>/accept/', InvoiceAcceptView.as_view(), name='b2b-invoices-accept'),
    path('invoices/accept', InvoiceAcceptView.as_view(), name='b2b-invoices-accept-legacy-no-slash'),
    path('invoices/accept/', InvoiceAcceptView.as_view(), name='b2b-invoices-accept-legacy'),
    # Inventory (canonical + legacy)
    path('inventory/reserve', ReserveView.as_view(), name='b2b-inventory-reserve-no-slash'),
    path('inventory/reserve/', ReserveView.as_view(), name='b2b-inventory-reserve'),
    path('inventory/unreserve', UnreserveView.as_view(), name='b2b-inventory-unreserve-no-slash'),
    path('inventory/unreserve/', UnreserveView.as_view(), name='b2b-inventory-unreserve'),
    path('inventory/fulfill', FulfillView.as_view(), name='b2b-inventory-fulfill-no-slash'),
    path('inventory/fulfill/', FulfillView.as_view(), name='b2b-inventory-fulfill'),
    path('reserve', ReserveView.as_view(), name='b2b-reserve-no-slash'),
    path('reserve/', ReserveView.as_view(), name='b2b-reserve'),
    path('unreserve', UnreserveView.as_view(), name='b2b-unreserve-no-slash'),
    path('unreserve/', UnreserveView.as_view(), name='b2b-unreserve'),
    path('fulfill', FulfillView.as_view(), name='b2b-fulfill-no-slash'),
    path('fulfill/', FulfillView.as_view(), name='b2b-fulfill'),
    # Public catalog (B2C proxy source)
    path('public/products', PublicProductListView.as_view(), name='b2b-public-products-no-slash'),
    path('public/products/', PublicProductListView.as_view(), name='b2b-public-products'),
    path('public/products/batch', PublicProductBatchView.as_view(), name='b2b-public-products-batch-no-slash'),
    path('public/products/batch/', PublicProductBatchView.as_view(), name='b2b-public-products-batch'),
    path('public/products/<uuid:product_id>', PublicProductDetailView.as_view(), name='b2b-public-product-detail-no-slash'),
    path('public/products/<uuid:product_id>/', PublicProductDetailView.as_view(), name='b2b-public-product-detail'),
    path('public/products/<uuid:product_id>/similar', PublicProductSimilarView.as_view(), name='b2b-public-product-similar-no-slash'),
    path('public/products/<uuid:product_id>/similar/', PublicProductSimilarView.as_view(), name='b2b-public-product-similar'),
    path('public/skus/<uuid:sku_id>', PublicSkuDetailView.as_view(), name='b2b-public-sku-detail-no-slash'),
    path('public/skus/<uuid:sku_id>/', PublicSkuDetailView.as_view(), name='b2b-public-sku-detail'),
    # Moderation events (canonical + legacy)
    path('moderation/events', ModerationEventsView.as_view(), name='b2b-moderation-events-no-slash'),
    path('moderation/events/', ModerationEventsView.as_view(), name='b2b-moderation-events'),
    path('events/moderation', ModerationEventsView.as_view(), name='b2b-events-moderation-no-slash'),
    path('events/moderation/', ModerationEventsView.as_view(), name='b2b-events-moderation'),
]
