from django.urls import path

from .views import (
    AlsoBoughtView,
    BannerEventsView,
    B2BEventsView,
    CartItemDetailView,
    CartItemsView,
    CartMergeView,
    CartValidateView,
    CartView,
    CollectionProductsView,
    FavoriteDetailView,
    FavoritesView,
    FavoriteSubscribeView,
    HomeBannersView,
    MainCollectionsView,
    ProductEventsView,
)


urlpatterns = [
    path("cart", CartView.as_view(), name="cart-no-slash"),
    path("cart/", CartView.as_view(), name="cart"),
    path("cart/items", CartItemsView.as_view(), name="cart-items-no-slash"),
    path("cart/items/", CartItemsView.as_view(), name="cart-items"),
    path("cart/items/<uuid:sku_id>", CartItemDetailView.as_view(), name="cart-item-detail-no-slash"),
    path("cart/items/<uuid:sku_id>/", CartItemDetailView.as_view(), name="cart-item-detail"),
    path("cart/validate", CartValidateView.as_view(), name="cart-validate-no-slash"),
    path("cart/validate/", CartValidateView.as_view(), name="cart-validate"),
    path("cart/merge", CartMergeView.as_view(), name="cart-merge-no-slash"),
    path("cart/merge/", CartMergeView.as_view(), name="cart-merge"),
    path("favorites", FavoritesView.as_view(), name="favorites-no-slash"),
    path("favorites/", FavoritesView.as_view(), name="favorites"),
    path("favorites/<uuid:product_id>", FavoriteDetailView.as_view(), name="favorites-detail-no-slash"),
    path("favorites/<uuid:product_id>/", FavoriteDetailView.as_view(), name="favorites-detail"),
    path("favorites/<uuid:product_id>/subscribe", FavoriteSubscribeView.as_view(), name="favorites-subscribe-no-slash"),
    path("favorites/<uuid:product_id>/subscribe/", FavoriteSubscribeView.as_view(), name="favorites-subscribe"),
    # B2B inbound events (canonical + legacy)
    path("b2b/events", B2BEventsView.as_view(), name="b2b-events-no-slash"),
    path("b2b/events/", B2BEventsView.as_view(), name="b2b-events"),
    path("events/product", ProductEventsView.as_view(), name="events-product-no-slash"),
    path("events/product/", ProductEventsView.as_view(), name="events-product"),
    # Legacy home/collections (proxied via catalog in gateway for new API)
    path("banner-events", BannerEventsView.as_view(), name="banner-events-no-slash"),
    path("banner-events/", BannerEventsView.as_view(), name="banner-events"),
    path("cart/also_bought", AlsoBoughtView.as_view(), name="cart-also-bought-no-slash"),
    path("cart/also_bought/", AlsoBoughtView.as_view(), name="cart-also-bought"),
    path("main/collections", MainCollectionsView.as_view(), name="main-collections-no-slash"),
    path("main/collections/", MainCollectionsView.as_view(), name="main-collections"),
    path("collections/<uuid:collection_id>/products", CollectionProductsView.as_view(), name="collection-products-no-slash"),
    path("collections/<uuid:collection_id>/products/", CollectionProductsView.as_view(), name="collection-products"),
    path("catalog/banners", HomeBannersView.as_view(), name="catalog-banners-no-slash"),
    path("catalog/banners/", HomeBannersView.as_view(), name="catalog-banners"),
]
